kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: kafka
  name: data-zk-0
  annotations: 
    volume.beta.kubernetes.io/storage-class: data
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 50Gi