# Allow developer tom access & operator to namespace dev 

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: dev
  name: common-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "services", "replicationcontrollers", "endpoints", "configmaps", "secrets"]
  verbs:     ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs:     ["create"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets", "statefulsets", "daemonsets"]
  verbs:     ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["cronjobs", "jobs"]
  verbs:     ["get", "list", "watch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: developer-reader
  namespace: dev
subjects:
- kind: User
  name: tom
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: common-reader
  apiGroup: rbac.authorization.k8s.io
